config/routes.rb
Rails.application.routes.draw do

  root "pages#index"
  resources :wines
  resources :users
  resources :wineries
  resources :tasting_notes

  get '/taste_wine' => "pages#taste_wine", as: :taste_wine

  get '/signup' => 'users#new', as: :signup
  post '/signup' => 'users#create'
  get '/signin' => 'authentication#new', as: :signin
  post '/signin' => 'authentication#create'
  get '/signout' => 'authentication#destroy', as: :signout

end

app/models/tasting_note.rb
class TastingNote < ActiveRecord::Base

  belongs_to :user
  belongs_to :wine

  validates :wine_rating, presence: true
  validates :wine_id, presence: true
  validate :rating_cannot_be_greater_than_5, on: [:create, :update]

  def rating_cannot_be_greater_than_5
    if wine_rating.present? && (wine_rating < 0 || wine_rating > 5)
      errors.add(:wine_rating, "Ratings can only be 0-5")
    end
  end

end

app/controllers/tasting_notes_controller.rb
class TastingNotesController < ApplicationController
  before_action :set_tasting_note, only: [:show, :edit, :update, :destroy]
  before_action :ensure_logged_in_user
  before_action :current_user_notes, only: [:show, :edit, :update, :destroy]

  def index
    @tasting_notes = TastingNote.all
  end

  def new
    @tasting_note = TastingNote.new
  end

  def create
    @tasting_note = TastingNote.new(tasting_notes_params)
    if @tasting_note.save
      redirect_to tasting_notes_path, notice: "Your note was successfully created!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @tasting_note.update(tasting_notes_params)
    if @tasting_note.save
      redirect_to tasting_note_path, notice: "Your note was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @tasting_note.destroy
    redirect_to tasting_notes_path, notice: "Your note was successfully deleted."
  end

  private
  def set_tasting_note
    @tasting_note = TastingNote.find(params[:id])
  end

  def tasting_notes_params
    params.required(:tasting_note).permit(
    :wine_rating,
    :color_depth,
    :color_hue,
    :color_clarity,
    :aroma_intensity,
    :aroma_age,
    :aromas,
    :taste_dry,
    :taste_body,
    :taste_acid,
    :taste_tannin,
    :taste_balance,
    :taste_intensity,
    :flavors,
    :taste_finish,
    :notes,
    :wine_id,
    :user_id,
    :date
    )
  end

end

app/views/tasting_notes/_form.html.erb
<div class="page-header">
  <h1><%= title %></h1>
</div>

<div class="form">
  <%= form_for @tasting_note do |f| %>

  <%= render 'shared/errors', instance: @tasting_note %>

  <div class="form-group">
    <%= f.collection_select(:wine_id, Wine.all, :id, :name,
    {include_blank: "Please select a wine"}, {class: "form-control"}) %>
  </div>

  <p>
    If your wine isn't available, please add it
    <strong><%= link_to "here", new_wine_path %></strong> first.
  </p>

  <div class="row form-group">
    <div class="form-group">
      <%= f.label :wine_rating, "Rating", class: "col-sm-2 control-label" %>
      <div class= "col-sm-2">
        <%= f.number_field :wine_rating, class: "form-control" %>
      </div>
      <div class= "col-sm-4">
        <p>
          Please rate wine 0-5, with 5 being the best!
        </p>
      </div>

    </div>
  </div>

  <div class="row form-group">
    <div class="form-group">
      <%= f.label :date, "Tasting Date", class: "col-sm-2 control-label" %>
      <div class= "col-sm-2">
        <%= f.date_field :date, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h2 class="panel-title">
            Color
          </h2>
        </div>
        <div class="panel-body">
          <% if current_user.advanced? || current_user.admin? %>
            <div class="row form-group">
              <%= f.label :color_depth, "Depth", class: "col-sm-4 control-label" %>
              <div class= "col-sm-8">
                <%= f.select(:color_depth, ["watery", "light", "medium", "deep", "dark"],
                {include_blank: :true}, {class: "form-control"}) %>
              </div>
            </div>
          <% end %>

          <div class="row form-group">
            <%= f.label :color_hue, "Hue", class: "col-sm-4 control-label"%>
            <div class= "col-sm-8">
              <%= f.select(:color_hue, ["greenish", "yellow", "straw yellow", "gold", "amber",
                "pink", "salmon", "orange", "copper",
                "purpleish", "ruby", "red", "garnet", "brick", "brown"],
              {include_blank: :true}, {class: "form-control"}) %>
            </div>
          </div>

          <% if current_user.advanced? || current_user.admin? %>
            <div class="row form-group">
              <%= f.label :color_clarity, "Clarity", class: "col-sm-4 control-label" %>
              <div class= "col-sm-8">
                <%= f.select(:color_clarity, ["clear", "slight haze", "cloudy"],
                {include_blank: :true}, {class:"form-control"}) %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      
      <div class="panel panel-info">
        <div class="panel-heading">
          <h2 class="panel-title">
            Aroma
          </h2>
        </div>
        <div class="panel-body">
          <% if current_user.advanced? || current_user.admin? %>
            <div class="row form-group">
              <%= f.label :aroma_intensity, "Intensity", class: "col-sm-4 control-label"  %>
              <div class= "col-sm-8">
                <%= f.select(:aroma_intensity, ["low", "medium", "powerful"],
                {include_blank: :true}, {class: "form-control"})%>
              </div>
            </div>

            <div class="row form-group">
              <%= f.label :aroma_age, "Age", class: "col-sm-4 control-label" %>
              <div class= "col-sm-8">
                <%= f.select(:aroma_age, ["young", "some age", "aged"],
                {include_blank: :true}, {class: "form-control"}) %>
              </div>
            </div>
          <% end %>

          <div class="row form-group">
            <%= f.label :aromas, "List Aromas", class: "col-sm-4 control-label" %>
            <div class= "col-sm-8">
              <%= f.text_area :aromas, class:"form-control" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h2 class="panel-title">
            Taste
          </h2>
        </div>
        <div class="panel-body">
          <div class="row form-group">
            <%= f.label :taste_dry, "Dry/Sweet", class: "col-sm-4 control-label" %>
            <div class="col-sm-8">
              <%= f.select(:taste_dry, ["extremely dry", "dry", "off dry", "medium sweet", "sweet", "very sweet"],
              {include_blank: :true}, {class:"form-control"}) %>
            </div>
          </div>
          <% if current_user.advanced? || current_user.admin? %>
            <div class="row form-group">
              <%= f.label :taste_body, "Body", class: "col-sm-4 control-label" %>
              <div class="col-sm-8">
                <%= f.select(:taste_body, ["very light", "light", "medium", "medium-full", "full-bodied", "heavy or thick"],
                {include_blank: :true}, {class: "form-control"}) %>
              </div>
            </div>

            <div class="row form-group">
              <%= f.label :taste_acid, "Acidity", class:"col-sm-4 control-label" %>
              <div class="col-sm-8">
                <%= f.select(:taste_acid, ["none", "tart", "crisp", "smooth"],
                {include_blank: :true}, {class: "form-control"}) %>
              </div>
            </div>

            <div class="row form-group">
              <%= f.label :taste_tannin, "Tannin (if any)", class:"col-sm-4 control-label" %>
              <div class= "col-sm-8">
                <div class="form-group off-set-col-sm-2">
                  <%= f.select(:taste_tannin, ["low", "medium", "high"],
                  {include_blank: "Level"}, {class: "form-control"}) %>
                </div>
                <div class="off-set-col-sm-2">
                  <%= f.select(:taste_tannin, ["soft", "round", "dry", "abrasive" ],
                  {include_blank: "Type"}, {class: "form-control"}) %>
                </div>
              </div>
            </div>

            <div class="row form-group">
              <%= f.label :taste_balance, "Balance", class:"col-sm-4 control-label" %>
              <div class="col-sm-8">
                <div class="form-group">
                  <%= f.select(:taste_balance, ["good", "okay", "unbalanced"],
                  {include_blank: :true}, {class: "form-control"}) %>
                </div>
                <div class="off-set-col-sm-2">
                  <p>
                    If unbalanced, why? Too much alcohol, acid, tannin, and/or sugar?
                  </p>
                </div>
                <div class="off-set-col-sm-2">
                  <%= f.text_field :taste_balance, class: "form-control" %>
                </div>
              </div>
            </div>
          <% end %>
          <div class="row form-group">
            <%= f.label :flavors, "Flavors", class: "col-sm-4 control-label" %>
            <div class="col-sm-8">
              <%= f.text_area :flavors, class: "form-control" %>
            </div>
          </div>

          <% if current_user.advanced? || current_user.admin? %>
            <div class="row form-group">
              <%= f.label :taste_finish, "Finish", class: "col-sm-4 control-label" %>
              <div class="col-sm-8">
                <%= f.select(:taste_finish, ["short/none", "medium", "long", "very long"],
                {include_blank: :true}, {class: "form-control"}) %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :notes, "Notes", class: "col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.text_area :notes, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.submit button_name, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <% end %>

app/views/tasting_notes/edit.html.erb
<%= render 'form', title: "Edit Tasting Note", button_name: "Update Tasting Note" %>

app/views/tasting_notes/index.html.erb
<div class="page-header">
  <h1>Tasting Notes</h1>
</div>

<table class= "table">
  <thead>
    <tr>
      <td>
        Date
      </td>
      <td>
        Rating
      </td>
      <td>
        Name
      </td>
      <td>
        Winery
      </td>
      <td>
        Flavors
      </td>
      <td>
        Notes
      </td>
    </tr>
  </thead>
  <tbody>
    <% if current_user.admin == true %>
      <% @tasting_notes.each do |note| %>
      <tr>
        <td>
          <% if note.date.present? %>
            <%= note.date.strftime("%m/%d/%Y") %>
          <% end %>
        </td>
        <td>
          <%= note.wine_rating %>
        </td>
        <td>
          <%= link_to note.wine.name, tasting_note_path(note) %>
        </td>
        <td>
          <%= link_to note.wine.winery.name, winery_path(note.wine.winery) %>
        </td>
        <td>
          <%= note.flavors %>
        </td>
        <td>
          <%= note.notes %>
        </td>
        <td>
          <%= link_to "Edit", edit_tasting_note_path(note) %>
        </td>
        <td>
          <%= link_to "Delete", tasting_note_path(note), method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
        </tr>
        <% end %>
      <% else %>
        <% current_user.tasting_notes.each do |note| %>
        <tr>
          <td>
            <% if note.date.present? %>
              <%= note.date.strftime("%m/%d/%Y") %>
            <% end %>
          </td>
          <td>
            <%= note.wine_rating %>
          </td>
          <td>
            <%= link_to note.wine.name, tasting_note_path(note) %>
          </td>
          <td>
            <%= link_to note.wine.winery.name, winery_path(note.wine.winery) %>
          </td>
          <td>
            <%= note.flavors %>
          </td>
          <td>
            <%= note.notes %>
          </td>
          <td>
            <%= link_to "Edit", edit_tasting_note_path(note) %>
          </td>
          <td>
            <%= link_to "Delete", tasting_note_path(note), method: :delete, data: {confirm: "Are you sure?"} %>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

app/views/tasting_notes/new.html.erb
<%= render 'form', title: "New Tasting Note", button_name: "Add Tasting Note" %>

app/views/tasting_notes/show.html.erb
<div class="page-header left">
  <div class="pull-right">
    <%= link_to "Edit", edit_tasting_note_path(@tasting_note) %>    |
    <%= link_to "Delete", tasting_note_path(@tasting_note), method: :delete,
    data: {confirm: "Are you sure?"} %>
    <% if @tasting_note.date.present? %>
      <p>
        Last Tasted: <%= @tasting_note.date.strftime("%m/%d/%Y") %>
      </p>
    <% end %>
  </div>
  <h1>
    <%= @tasting_note.wine.name %>
  </h1>
</div>

<% if @tasting_note.wine_rating.present? %>
<div class="row">
  <div class="col-md-6">
    <h3 class="pull-left">Rating: <%= @tasting_note.wine_rating %></h3>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">
          Details
        </h2>
      </div>
      <div class="panel-body">
        <p>
          <strong>Varietal:</strong>
          <%= @tasting_note.wine.grape_varietal %>
        </p>
        <p>
          <strong>Year:</strong>
          <%= @tasting_note.wine.year %>
        </p>
        <p>
          <strong>Winery:</strong>
          <%= link_to @tasting_note.wine.winery.name, winery_path(@tasting_note.wine.winery) %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">
          Notes
        </h2>
      </div>
      <div class="panel-body">
        <p>
          <%= @tasting_note.notes %>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">Color</h2>
      </div>
      <div class="panel-body">
        <% if current_user.advanced? || current_user.admin? %>
          <p>
            <strong>Depth:</strong> <%= @tasting_note.color_depth %>
          </p>
        <% end %>
        <p>
          <strong>Hue:</strong> <%= @tasting_note.color_hue %>
        </p>
        <% if current_user.advanced? || current_user.admin? %>
          <p>
            <strong>Clarity:</strong> <%= @tasting_note.color_clarity %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">Aroma</h2>
      </div>
      <div class="panel-body">
        <% if current_user.advanced? || current_user.admin? %>
          <p>
            <strong>Intensity:</strong> <%= @tasting_note.aroma_intensity %>
          </p>
          <p>
            <strong>Age:</strong> <%= @tasting_note.aroma_age %>
          </p>
        <% end %>
        <p>
          <strong>List Aromas:</strong> <%= @tasting_note.aromas %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">Taste</h2>
      </div>
      <div class="panel-body">
        <p>
          <strong>Dry/Sweet:</strong> <%= @tasting_note.taste_dry %>
        </p>
        <% if current_user.advanced? || current_user.admin? %>
          <p>
            <strong>Body:</strong> <%= @tasting_note.taste_body %>
          </p>
          <p>
            <strong>Acidity:</strong> <%= @tasting_note.taste_acid %>
          </p>
          <p>
            <strong>Tannin (if any):</strong> <%= @tasting_note.taste_tannin %>
          </p>
          <p>
            <strong>Balance:</strong> <%= @tasting_note.taste_balance %>
          </p>
        <% end %>
        <p>
          <strong>Flavors:</strong> <%= @tasting_note.flavors %>
        </p>
        <% if current_user.advanced? || current_user.admin? %>
          <p>
            <strong>Finish:</strong> <%= @tasting_note.taste_finish %>
          </p>
        <% end %>
      </div>
    </div>
    </div>
  </div>
</div>