config/routes.rb
Rails.application.routes.draw do

  root "pages#index"
  resources :wines
  resources :users
  resources :wineries
  resources :tasting_notes

  get '/taste_wine' => "pages#taste_wine", as: :taste_wine

  get '/signup' => 'users#new', as: :signup
  post '/signup' => 'users#create'
  get '/signin' => 'authentication#new', as: :signin
  post '/signin' => 'authentication#create'
  get '/signout' => 'authentication#destroy', as: :signout

end

app/models/winery.rb
class Winery < ActiveRecord::Base
  mount_uploader :winery_pic, WineryPicUploader

  validates :name, presence: true

  has_many :wines

  def full_address
    "#{street}, #{city}, #{state} #{zip}"
  end

  def upload
    uploaded_io = params[:winery][:winery_pic]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    w = Winery.new
    w.winery_pic = params[:file]
    w.save!

  end



end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController
  before_action :set_winery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_logged_in_user, except: [:index, :show]
  before_action :only_admin, only: [:edit, :update, :destroy]

  def index
    @wineries = Winery.all
  end

  def new
    @winery = Winery.new
  end

  def create
    @winery = Winery.new(winery_params)
    if @winery.save
      redirect_to wineries_path, notice: "Winery was successfully created. New wineries will not appear on the site until they are approved by an admin."
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @winery.update(winery_params)
    if @winery.save
      redirect_to wineries_path, notice: "Winery was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @winery.destroy
    redirect_to wineries_path, notice: "Winery was successfully deleted"
  end

private

  def winery_params
    params.required(:winery).permit(
    :name,
    :street,
    :city,
    :zip,
    :state,
    :county,
    :hours,
    :phone_number,
    :email,
    :rating,
    :description,
    :winery_pic,
    :website,
    :yelp_id,
    :wine_id,
    :approved,
    :lat,
    :long,
    :wine_list
    )
  end


  def set_winery
    @winery = Winery.find(params[:id])
  end

end

app/views/wineries/_form.html.erb
<div class="page-header">
  <h1><%= title %></h1>
</div>

<div class="form">
  <%= form_for(@winery) do |f| %>

  <%= render "shared/errors", instance: @winery %>

  <div class="row form-group">
    <%= f.label :name, "Name*", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control"  %>
    </div>

    <%= f.label :description, "Description", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_area :description, class: "form-control"  %>
    </div>
  </div>

  <div class="row form-group">
    <%= f.label :street, "Street*", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :street, class: "form-control"  %>
    </div>

    <%= f.label :city, "City*", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :city, class: "form-control"  %>
    </div>
  </div>

  <div class="row form-group">
    <%= f.label :state, "State*", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :state, class: "form-control"  %>
    </div>

    <%= f.label :zip, "Zip*", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :zip, class: "form-control"  %>
    </div>
  </div>

  <div class="row form-group">
    <%= f.label :county, "County", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :county, class: "form-control"  %>
    </div>

    <%= f.label :hours, "Hours", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :hours, class: "form-control"  %>
    </div>
  </div>

  <div class="row form-group">
    <%= f.label :phone_number, "Phone Number*", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :phone_number, class: "form-control"  %>
    </div>

    <%= f.label :email, "Email", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.email_field :email, class: "form-control"  %>
    </div>
  </div>

  <div class="row form-group">
    <%= f.label :website, "Website", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :website, class: "form-control" %>
    </div>

    <%= f.label :winery_pic, "Picture", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.file_field :winery_pic, class: "form-control" %>
    </div>
  </div>

  <% if current_user && current_user.admin %>
  <div class="row form-group">
    <%= f.label :approved, "Approved?", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.check_box :approved, class: "form-control" %>
    </div>
  </div>
  <% end %>

  <div class="row form-group">
    <%= f.submit button_name, class: "btn btn-primary"%>
  </div>
  <% end %>
</div>

app/views/wineries/edit.html.erb
<%= render 'form', button_name:"Update Winery", title: "Edit Winery" %>

app/views/wineries/index.html.erb
<div class="page-header">
  <h1>Colorado Wineries</h1>
</div>

<table class= "table">
  <thead>
    <tr>
      <td>
        Name
      </td>
      <td>
        Website
      </td>
      <td>
        City
      </td>
      <% if current_user && current_user.admin? %>
      <td>
        Approved?
      </td>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% if current_user && current_user.admin? %>
    <% @wineries.sort.each do |winery| %>
      <% if (winery.approved==false) %>
        <tr class= "alert alert-danger">
          <td>
            <%= link_to winery.name, winery_path(winery) %>
          </td>
          <td>
            <%= link_to winery.website, "http://#{winery.website}" %>
          </td>
          <td>
            <%= winery.city %>
          </td>
          <td>
            <%= winery.approved %>
          </td>
          <td><%= link_to "Edit", edit_winery_path(winery) %></td>
          <td><%= link_to "Delete", winery, method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
      <% else %>
        <tr>
          <td>
            <%= link_to winery.name, winery_path(winery) %>
          </td>
          <td>
            <%= link_to winery.website, "http://#{winery.website}" %>
          </td>
          <td>
            <%= winery.city %>
          </td>
            <td>
              <%= winery.approved %>
            </td>
            <td><%= link_to "Edit", edit_winery_path(winery) %></td>
            <td><%= link_to "Delete", winery, method: :delete, data: {confirm: "Are you sure?"} %></td>
          </tr>
      <% end %>
      <% end %>
    <% else %>
      <% @wineries.sort.each do |winery| %>
        <% if winery.approved == true %>
          <tr>
            <td>
              <%= link_to winery.name, winery_path(winery) %>
            </td>
            <td>
              <%= winery.website %>
            </td>
            <td>
              <%= winery.city %>
            </td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
    </tbody>
  </table>

app/views/wineries/new.html.erb
<%= render 'form', title: "Add Winery", button_name: "Add Winery" %>

app/views/wineries/show.html.erb
<div class="page-header left">
  <h1><%= @winery.name %></h1>
</div>

<div class="row">
  <!-- <% if @winery.winery_pic.present? %>
    <%= image_tag @winery.winery_pic, class: "img-responsive img-thumbnail" %>
  <% end %> -->

  <% YelpAPI.new.search({ term: 'wineries'}).businesses.each do |winery| %>
    <% if winery.id == @winery.yelp_id %>
      <p class="text-left">
        <strong>Rating:</strong> <%= image_tag winery.rating_img_url_small %>
      </p>
      <p class="text-left">
        <%= winery.review_count %> <%= image_tag("reviewsFromYelpRED.gif") %>
      </p>
      <p class="text-left">
        <strong>Yelp site:</strong> <%= link_to winery.url, winery.url %>
      </p>
    <% end %>
  <% end %>
  <p class="text-left">
    <strong>Address:</strong> <%= @winery.full_address %>
  </p>
  <p class="text-left">
    <strong>Hours:</strong> <%= @winery.hours %>
  </p>
  <p class="text-left">
    <strong>Phone Number:</strong> <%= @winery.phone_number %>
  </p>
  <p class="text-left">
    <strong>Email:</strong> <%= mail_to(@winery.email) %>
  </p>
  <p class="text-left">
    <strong>Website:</strong> <%= link_to @winery.website, "http://#{@winery.website}" %>
  </p>
  <p class="text-left">
    <strong>Description:</strong> <%= @winery.description %>
  </p>
  <p class="text-left">
    <strong>Wines:</strong> <%= @winery.wine_list %>
  </p>
</div>