config/routes.rb
Rails.application.routes.draw do

  root "pages#index"
  resources :wines
  resources :users
  resources :wineries
  resources :tasting_notes

  get '/taste_wine' => "pages#taste_wine", as: :taste_wine

  get '/signup' => 'users#new', as: :signup
  post '/signup' => 'users#create'
  get '/signin' => 'authentication#new', as: :signin
  post '/signin' => 'authentication#create'
  get '/signout' => 'authentication#destroy', as: :signout

end

app/models/wine.rb
class Wine < ActiveRecord::Base
  mount_uploader :wine_pic, WinePicUploader

  validates :grape_varietal, presence: true
  validates :name, presence: true
  validates :winery_id, presence: true

  belongs_to :winery
  has_many :tasting_notes


  def self.varietals
    [
      'Barbera',
      'Cabernet Franc',
      'Cabernet Sauvingnon',
      'Chardonnay',
      'Grenache',
      'Gewurztraminer',
      'Malbec',
      'Marsanne',
      'Merlot',
      'Mourvedre',
      'Muscat',
      'Petite Sirah',
      'Petite Verdot',
      'Pinot Noir',
      'Pinot Gris',
      'Riesling',
      'Roussanne',
      'Sangiovese',
      'Sauvignon Blanc',
      'Semillon',
      'Syrah',
      'Shiraz',
      'Tannat',
      'Tempranillo',
      'Viognier',
      'Zinfandel',
      'Blend',
      'Other'
    ]
  end

  def self.states
    [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Flordia',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virgina',
      'Wisconsin',
      'Wyoming'
    ]
  end



end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :ensure_logged_in_user, except: [:index, :show]
  before_action :only_admin, only: [:edit, :update, :destroy]

  def index
    @wines = Wine.all
  end

  def new
    @wine = Wine.new
  end

  def create
    @wine = Wine.new(wine_params)
    if @wine.save
      redirect_to wines_path, notice: 'Wine was successfully added.'
    else
      render :new
    end
  end

  def edit
    @wine = Wine.find(params[:id])
  end

  def update
    @wine = Wine.find(params[:id])
    @wine.update(wine_params)
    if @wine.save
      redirect_to wines_path, notice: 'Wine was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @wine = Wine.find(params[:id])
  end

  def destroy
    @wine = Wine.find(params[:id])
    @wine.destroy
    redirect_to wines_path, notice: 'Wine was successfully deleted.'
  end

private

  def wine_params
    params.required(:wine).permit(
    :grape_varietal,
    :country,
    :state,
    :vineyard,
    :year,
    :rating,
    :name,
    :winery_id,
    :tasting_notes_id,
    :wine_pic
    )
  end

end

app/views/wines/_form.html.erb
<div class="form-horizontal">
  <%= form_for(@wine) do |f| %>

  <%= render "shared/errors", instance: @wine %>

  <div class="form-group">
    <%= f.label :name, "Name*", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="col-sm-4">
      <p>
        Please format it like this: "Name (Winery)"
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :winery_id, "Winery*", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.collection_select(:winery_id, Winery.all, :id, :name, {include_blank: :true}, {class: "form-control"}) %>
    </div>
    <div class="col-sm-4">
      <p>
        If your winery isn't here, please suggest a new winery <%= link_to "here", new_winery_path %>!
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :grape_varietal, "Grape Varietal*", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.select :grape_varietal, Wine.varietals, {include_blank: :true}, {class: "form-control"} %>
    </div>
    <div class="col-sm-4">
      <p>
        For blends, either choose the primary varietal or blend.
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :state, "State", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.select :state, Wine.states, {include_blank: "Colorado"}, {class: "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :vineyard, "Vineyard", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :vineyard, class: "form-control"  %>
    </div>
    <div class="col-sm-4">
      <p>
        Might be the same as the winery.
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :year, "Year", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.number_field :year, class: "form-control"  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :wine_pic, "Picture", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.file_field :wine_pic, class: "form-control" %>
    </div>
    <div class="col-sm-4">
      <p>
        Feel free to add pictures of the label or in a glass.
      </p>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit name: button_name, class: "btn btn-primary"%>
  </div>
  <br/>
  <% end %>
</div>

app/views/wines/edit.html.erb
<div class="page-header">
  <h1>Edit Wine</h1>
</div>

<%= render 'form', button_name: "Update Wine" %>

app/views/wines/index.html.erb
<div class="page-header">
  <h1>Colorado Wines</h1>
</div>
<br/>
<table class= "table">
  <thead>
    <tr>
      <td>Rating</td>
      <td>
        Name
      </td>
      <td>
        Winery
      </td>
      <td>Grape Varietal</td>
      <td>Year</td>
    </tr>
  </thead>
  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <% if wine.tasting_notes.present? %>
          <td>
            <%= number_with_precision(wine.tasting_notes.average(:wine_rating), precision: 2) %>
          </td>
        <% else %>
          <td>
            n/a
          </td>
        <% end %>
        <td>
          <%= link_to wine.name, wine_path(wine) %>
        </td>
        <td>
          <%= link_to wine.winery.name, winery_path(wine.winery.id) %>
        </td>
        <td><%= wine.grape_varietal %></td>
        <td><%= wine.year %></td>
        <% if current_user && current_user.admin? %>
          <td><%= link_to "Edit", edit_wine_path(wine) %></td>
          <td><%= link_to "Delete", wine, method: :delete, data: {confirm: "Are you sure?"} %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/wines/new.html.erb
<div class="page-header">
  <h1>Add Wine</h1>
</div>

<%= render 'form', button_name:"Add Wine" %>

app/views/wines/show.html.erb
<div class="page-header">
  <h1><%= @wine.name %></h1>
</div>

<div class="row">
  <% if @wine.wine_pic.present? %>
  <div class="col-sm-6">
    <%= image_tag @wine.wine_pic, class: "img-responsive img-thumbnail" %>
  </div>
  <% end %>
  <p class="text-left">
    <strong>Rating:</strong>
    <% if @wine.tasting_notes.present? %>
      <td>
        <%= number_with_precision(@wine.tasting_notes.average(:wine_rating), precision: 2) %>
      </td>
    <% else %>
      <td>
        n/a
      </td>
    <% end %>

  </p>
  <p class="text-left">
    <strong>Winery:</strong> <%= link_to @wine.winery.name, winery_path(@wine.winery_id) %>
  </p>
  <p class="text-left">
    <strong>Grape Varietal:</strong> <%= @wine.grape_varietal %>
  </p>
  <p class="text-left">
    <strong>Vineyard:</strong> <%= @wine.vineyard %>
  </p>
  <p class="text-left">
    <strong>Year:</strong> <%= @wine.year %>
  </p>
</div>