config/routes.rb
Rails.application.routes.draw do

  root "pages#index"
  resources :wines
  resources :users
  resources :wineries
  resources :tasting_notes

  get '/taste_wine' => "pages#taste_wine", as: :taste_wine

  get '/signup' => 'users#new', as: :signup
  post '/signup' => 'users#create'
  get '/signin' => 'authentication#new', as: :signin
  post '/signin' => 'authentication#create'
  get '/signout' => 'authentication#destroy', as: :signout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wine Tracker</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>

</head>
<body>
  <header class="navbar">
    <div class="container">
      <nav class="navbar navbar-collapse navbar-inverse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Wine Tracker", root_path %></li>
          <% if current_user %>
          <li><%= link_to current_user.name, user_path(current_user) %></li>
          <li><%= link_to "Sign Out", signout_path %></li>
          <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Show Wines", wines_path %></li>
            <li><%= link_to "Show Wineries", wineries_path %></li>
            <li><%= link_to "How to Taste", taste_wine_path %></li>
          </ul>
        </ul>
      </nav>
      <% if current_user %>
      <nav class="navbar navbar-collapse">
        <ul class= "nav navbar-nav">
          <% if current_user && current_user.admin %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Add Winery", new_winery_path %></li>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Add Tasting Note", new_tasting_note_path %></li>
            <li><%= link_to "My Tasting Notes", tasting_notes_path %> </li>
            <li><%= link_to "Add Wine", new_wine_path %> </li>
          </ul>
        </ul>
      </nav>
      <% end %>
    </div>
  </header>
  <%= notice %>
  <div class="container">
    <%= yield %>
    <hr>
    <div class="footer">
      Copyright &copy; <%= Time.zone.today.year %> Beth Jaswa |
      <%= link_to "http://www.linkedin.com/in/bethjaswa/" do %>
      <%= image_tag("linked_in.png") %>
      <% end %> |
      <%= link_to "http://www.twitter.com/@figmentbml" do %>
      <%= image_tag("Twitter_logo.png") %>
      <% end %> |
    </div>
  </div>
</body>

</html>